export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    ABOUT: '/about',
    COURSES: '/courses',
    GALLERY: '/gallery',
    CONTACT: '/contact',
    REGISTER: '/register',
  },
  AUTH: {
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    PENDING_APPROVAL: '/pending-approval',
    REJECTED: '/rejected',
  },
  STUDENT: {
    DASHBOARD: '/dashboard',
    PROFILE: '/dashboard/profile',
    FEES: '/dashboard/fees',
    COURSES: '/dashboard/courses',
    NOTIFICATIONS: '/dashboard/notifications',
    RECEIPTS: '/dashboard/receipts',
    SETTINGS: '/dashboard/settings',
  },
  ADMIN: {
    DASHBOARD: '/admin',
    STUDENTS: '/admin/students',
    ADMISSIONS: '/admin/admissions',
    COURSES: '/admin/courses',
    FEES: '/admin/fees',
    GALLERY: '/admin/gallery',
    CMS: '/admin/cms',
    CMS_HOMEPAGE: '/admin/cms/homepage',
    CMS_ABOUT: '/admin/cms/about',
    CMS_TESTIMONIALS: '/admin/cms/testimonials',
    CMS_FAQS: '/admin/cms/faqs',
    CMS_FOOTER: '/admin/cms/footer',
    ANALYTICS: '/admin/analytics',
    SETTINGS: '/admin/settings',
  },
} as const;
